### ISSUE TITLE
Q.js now on public CDN

### ISSUE THREAD

**Issue by wardbell** [kriskowal/q#245]
This is FYI, not an issue. Not sure where it should go.

I uploaded v.0.9.2 to [cdnjs](http://cdnjs.com/), an open source, [GitHub based](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/q.js), freely available CDN, which accepts contributions of popular public libraries. Use "Search" to quickly find "q.js".

Especially useful when building [jsFiddles](http://jsfiddle.net/) (see my use of it in the external resources of [this fiddle](http://jsfiddle.net/wardbell/r2kcB/)).

Two URLs at this point:
- http://cdnjs.cloudflare.com/ajax/libs/q.js/0.9.2/q.js
- http://cdnjs.cloudflare.com/ajax/libs/q.js/0.9.2/q.min.js

Anyone can keep it up by submitting a pull request with the latest versions.

**Comment by stefek99** [comment]
Quick question...

https://cdnjs.com/libraries/q.js

https://cdnjs.cloudflare.com/ajax/libs/q.js/2.0.3/q.js

```var WeakMap = require("weak-map");```

Doesn't work in my browser....

**Comment by kriskowal** [comment]
Version 2 of Q is not released. It is in npm but not with the "latest" tag. Not sure how CDN.js deals with this, but I presume that the client picks the exact version they want.

**Comment by adjavaherian** [comment]
What's the proper way to get a Q from this library?  This example works in the browser, but it looks like the delay doesn't?  https://jsfiddle.net/dzzas97p/6/ 
Its funny, because the equivalent works as expected in Node

```javascript
// async_series.js
// example of using reduce and promises and closure to create async results in series

var q = require('Q');
var results = [1, 2, 3, 4, 5];

function workCollection(arr) {

    return arr.reduce(function(promise, item, index) {
        return promise.delay(1000).then(function(result) {
            console.log('item', item, 'result', result, 'index', index);
            return true;
		});
    }, q(true));

}

	q()
		.then(function(){
			console.log('start');
            return results
		})
        .then(workCollection)
        .then(function(){
            console.log('done');
        }, function(err){
            console.error(err);
        });

```

Perhaps my fiddle implementation is not equivalent?
