### ISSUE TITLE
Q.all with empty array never ends up

### ISSUE THREAD

**Issue by surr-name** [kriskowal/q#364]
Q.all( [] )
    .then(function(){console.log('success')})
    .fail(function(){console.log('failed')});

This shall never be resolved or rejeced.

**Comment by SET001** [comment]
Can some one explain why `Q.all( [] )` shall never be resolved or rejeced? In my case I have an array of initialisers and something should be done after all initialisers would finish it's jobs. So I can just do 

`Q.all(this.initializers).then(() => {`

and that something would run even if there are no any initialisers.

Now, that `all` does not resolve on empty array, I should move my post-init code to separate funciton and do something like this:

		if (this.initializers.length){
			Q.all(this.initializers).then(() => {
				this._run(controller);
			})
		} else {
			this._run(controller);
		}

**Comment by kriskowal** [comment]
@SET001 Q.all([]) should settle to [] immediately. There should be no need for the special case.

**Comment by SET001** [comment]
you mean it should be resolved?

**Comment by kriskowal** [comment]
@SET001 I mean resolved, settled, and fulfilled. A promise can be resolved with any other promise, including pending or "settled" promises. "settled" includes "fulfilled" or "rejected".

**Comment by SET001** [comment]
I may not understand you.

Here is a test case I made

```
	beforeEach(function(){
		foo = {
	 		controller: function(){}
	 	};
		spyOn(foo, 'controller').and.callThrough();
	});

	fit('should resolve empty promises array', function(){
		Q.all([]).then(
			foo.controller,
			foo.controller
		);
		expect(foo.controller).toHaveBeenCalled();
	});
```

and it always fails - not rejected and not resolved. Is it supposed behavior?
