### ISSUE TITLE
Is there a way to wait until any promise in an array finishes?

### ISSUE THREAD

**Issue by simonzack** [kriskowal/q#403]
I was trying to find a function in the api that did something like `.any([promise1, promise2, promise3])`, where if any of the 3 promises returned (succeeded or failed) the combined promise will return, but could not find an obvious way to do this.

**Comment by bergus** [comment]
@kriskowal 
> There is a relatively new API, `Q.race([promise1, promise2, promise3])`, but it may not have been documented yet. We’ll track that with this ticket.

It seems `race` is still not documented. Can you reopen?

**Comment by erights** [comment]
See also http://www.ecma-international.org/ecma-262/6.0/index.html#sec-promise.race
