### ISSUE TITLE
notify event behavior

### ISSUE THREAD

**Issue by torifat** [kriskowal/q#445]
I have a confusion regarding `notify`. I have seen a related issue but I think this one is slightly different.

So, for promises if it is already resolved then I can use it anywhere in my code later & get the value immediately. And if is not already resolved then I will get the value once it is resolved.

But, If I attach a handler after calling the notify then I don't get the current progress of the promise if I use it later in my code.

Is there any way around? Or I didn't understand the concept. I have tried with jQuery Promise and it's working fine. I'm aware that jQuery Promises are very different under the hood. But, Still just to compare I have put it below.
# Q

``` js
function get() {
    var deferred = Q.defer();
    deferred.notify('hello');
    setTimeout(function () {
        deferred.resolve('world!');
    }, 2000);
    return deferred.promise;
}

function doTheThing(data) {
    alert(data)
}

get().then(doTheThing, doTheThing, doTheThing);
```
# jQuery Promise

``` js
function get() {
    var deferred = $.Deferred();
    deferred.notify('hello');
    setTimeout(function () {
        deferred.resolve('world!');
    }, 2000);
    return deferred.promise();
}

function doTheThing(data) {
    alert(data)
}

get().then(doTheThing, doTheThing, doTheThing);
```

**Comment by ayeressian** [comment]
One possible ugly workaround would be to add setTimeout.
```javascript
function get() {
    var deferred = Q.defer();
    setTimeout(function() {
        deferred.notify('hello');
    });
    setTimeout(function () {
        deferred.resolve('world!');
    }, 2000);
    return deferred.promise;
}

function doTheThing(data) {
    alert(data)
}

get().then(doTheThing, doTheThing, doTheThing);
```
