### ISSUE TITLE
Sequential Q.all()

### ISSUE THREAD

**Issue by timjacobi** [kriskowal/q#606]
#### From the docs
"You can turn an array of promises into a promise for the whole, fulfilled array using `Q.all`"

"If you have a number of promise-producing functions that need to be run sequentially, you can [...] use the ultra-compact version. `return funcs.reduce(Q.when, Q(initialVal));`"

#### Problems
- The first approach returns a promise which eventually resolves to an array of values but it's not guaranteed to be sequential.
- The second approach is guaranteed to be sequential but returns a promise that eventually resolves to only one of the async calculated values.

#### Request
Provide a means of `Q.all()` which is guaranteed to execute sequentially

Please if I'm missing anything and you can do this already somehow, let me know! 
Thanks :)

**Comment by timjacobi** [comment]
Are there any plans to follow up on this?

**Comment by kriskowal** [comment]
@timjacobi I do not intend to incorporate this feature in Q. Q-IO provides this facility and if that is not satisfying, I recommend creating a library and adding it to our list https://github.com/kriskowal/q/wiki/Libraries

**Comment by dougmolineux** [comment]
Jamming a large array of promises into Q.all() isn't scalable (especially when you can't really tell how large it could grow). As a consequence we've been forced to not use it anywhere where we are unsure of the size of the array. In my opinion, A `Q.sequenceAll` would be an ideal and cleaner way to fix this, rather than using a custom reduce method. 

It is reasonable to assume that many small implementations of this method will probably not run into this issue, but as soon as we deployed our code to a production environment we ran into this issue in many places.

**Comment by kriskowal** [comment]
For long indefinite sequences of values, arrays and Q.all are the wrong
tool. You have to upgrade to streams. Q-IO (v2) provides a readable stream
that implements asynchronous forEach(), reduce(), all(), etc, with optional
concurrency limits, which beyond 1 concurrent operation, relax the ordering
constraint of the stream.

Streams are asynchronous iterators. I talk about this in an essay I wrote a
year ago, GToR github.com/kriskowal/gtor

Rough implementations exist for stream in the GToR repository and Q-IO v2
https://github.com/kriskowal/q-io/tree/v2

These are somewhat on the frontier, so bring a willingness to fix bugs and
contribute upstream or fork. This is an area where there’s opportunity to
leave a mark.

**Comment by danielmhair** [comment]
Thank you @dougmolineux  and @kriskowal for your last comments. @dougmolineux, for your thoughts about Q.all not being scalable for a large array of promises. Right before I read that, I was thinking the same thing, which is what led me to this issue. And @kriskowal, for your thoughts that we are doing it wrong by using `Q.all` for long indefinite sequences of values. It has inspired me to upgrade to streams.

**Comment by Wuntenn** [comment]
Just incase anyone else arrived here looking for a way to sequentially resolve a short list of promises, this [article](https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) may help (see: **Advanced mistake # 3: promises vs promise factories**)

**Comment by Cdvalencia** [comment]
posible [solution](https://gist.github.com/slavafomin/8ee69f447765bc5c5e19)
