### ISSUE TITLE
Large array passed into Q.all sometimes fails to be done

### ISSUE THREAD

**Issue by piglovesyou** [kriskowal/q#621]
This is an utility function proposal which ignores a formal Promise spec at all. Any advice would be glad.

### Problem

When we have a large array and do something with each item respectively, `Q.all` cannot handle them in terms of a memory error.

```js
var pool = [];
while (pool.length < 1000 * 1000) pool.push('yeah' + pool.length);

Q.all(pool.map(sampleTask))
.then(console.log.bind(null, 'done!'));

function sampleTask(item) {
  return Q().delay(1000).then(function() {
    return item + ' done';
  });
}

// XXX: FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Also, a large number of concurrent http requests can be load to a server.

```js
Error: socket hang up
    at createHangUpError (http.js:1476:15)
    at CleartextStream.socketCloseListener (http.js:1526:23)
    at CleartextStream.emit (events.js:117:20)
    at tls.js:693:10
    at process._tickCallback (node.js:419:13)
```

### Solution

If we can control the number of concurrency, that can resolve this problem. So how about we have such an utility in Q?

```js
Q.concurrent = concurrent;

Q.concurrent(sampleTask, pool, 4)
.then(console.log.bind(null, 'done!'));

function concurrent(task, pool, count) {
  var workers = [];
  var results = [];
  var needle = 0;
  while (workers.length < count) {
    workers.push(workIfAny());
  }
  return Q.all(workers).then(function() {
    return results;
  });
  function workIfAny() {
    if (needle < pool.length) {
      return Q.fcall(task, pool[needle++])
      .then(results.push.bind(results))
      .then(workIfAny);
    }
  }
}

```

**Comment by deanshub** [comment]
here is what i wrote as a workaround for now...
```javascript
var Q = require('q');

function limitedQ(){
	var methods={};

	methods.limitAll = function(self, method, values, limit){
		return Q.promise(function(resolve){
			var limitedPromises =[];

			while(values.length>0 && limitedPromises.length<limit){
				var args = values.shift();
				if (args instanceof Array){
					limitedPromises.push(method.apply(self,args));
				}else{
					limitedPromises.push(method.apply(self,[args]));
				}
			}

			Q.all(limitedPromises).then(function(limitedResults){
				if (limitedResults.length === 0){
					resolve(limitedResults);
				}else {
					methods.limitAll(self,method,values,limit).then(function(results){
						resolve(limitedResults.concat(results));
					});
				}
			});
		});
	};

	return methods;
}

module.exports = limitedQ();
```

**Comment by piglovesyou** [comment]
@deanshub I really understand what you'r doing because once I used to think of it just like you do. But `Q.consume` (#630) would be faster, because `Q.all` can contain a lazy time to wait for the slowest promise being fulfilled. So I used Producer-Consumer Pattern to reduce that overhead time. In addition, sometimes we want to keep an array of `values` itself so it's good idea not to use `values.shift()`.

**Comment by deanshub** [comment]
@piglovesyou your'e absolutely right, any idea when it will be merged?
Great name btw :smiley:

**Comment by piglovesyou** [comment]
@deanshub I don't know, I'm really interested in how the core developers think about this issue.

**Comment by kriskowal** [comment]
This problem should be solved in libraries. In Q-IO, I’m introducing an asynchronous iterator or stream reader. Such readers implement map, filter, forEach, all, &c and accept a concurrency limit argument beyond the standard Array method arguments, e.g., `new Reader([async?][iterable?]source).map(fn, thisp, concurrency)`.

**Comment by ramakrishnan** [comment]
Hi is parallel task processing with concurrency available in the latest code?

**Comment by ramakrishnan** [comment]
@kriskowal I am expecting a function similar to q.all which can take an argument to limit the concurrency limit. Is it available here?

**Comment by kriskowal** [comment]
@ramakrishnan That is available in Q-IO, but not in Q proper, but only in the experimental v2 releases. I’ve run up against the ceiling of how much time I have to maintain further packages, so anyone willing to pare that out and own it, or backport it to Q-IO v1 and join the contributors/publishers for that package. Anyone willing to provide assistance in bringing v2 out of experimental phase should follow me on twitter and try to join me for open source office hours, which I usually hold every other Sunday at 14:00 PST.

**Comment by piglovesyou** [comment]
> That is available in Q-IO,

@kriskowal I will try to help, but I need more info. I read `q-io/reader.js`. Although I understand what "asynchronous iterator" means, I couldn't find the idea of "concurrency limit" because it only wraps a native stream object and uses "data" event. Which code can exactly makes me know what's in your mind?

**Comment by kriskowal** [comment]
@piglovesyou The thin wrapper for node/reader just pumps data into a buffer. The stream uses two promise queues internally, one of which provides promises for the write side, and the other provides promises for the read side. The buffer's size is the number of pre-solved promises in the queue to the writer. The `map`, `forEach`, `reduce` etc methods all accept a third argument which is the concurrency limit. This gets passed into the buffer constructor. I wish I had more time to help. I wrote about the general idea here[1], which may help. The code is a bit of a mess and has at least one known bug. Please follow-up in the Q-IO issue tracker to keep Q notifications relevant for its contributors.

[1]: https://github.com/kriskowal/gtor

**Comment by piglovesyou** [comment]
Thank you (sorry I've read only `q-io@1`). I'll read v2 code more.

**Comment by heipei** [comment]
Hey @piglovesyou any updates on this? This was ages ago, still haven't across an idiomatic way to limit concurrency with Q (or any array of promises for that matter). Suggestions? I saw that your PR is still open.

**Comment by piglovesyou** [comment]
@heipei No I have not, I didn't dive into `q-io@2` because I didn't figure out what exactly @kriskowal suggested me in q-io, afterwards..
