### ISSUE TITLE
Using Q 1.1.2 in Firefox add-on content script is not possible

### ISSUE THREAD

**Issue by joscha** [kriskowal/q#631]
When using Q in a Firefox add-on content script, the following error shows up in the Firefox developer console:

```console
"({port:{emit: [..] {    [native code]}}) is not extensible"
```
This is due to [Q writing itself onto the `self` global object](https://github.com/kriskowal/q/blob/v1/q.js#L58) which is defined for Firefox content scripts (see [Firefox add-ons documentation](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts/using_port#Accessing_port)) though is not the standard `window` object, but the Firefox add-on native object to message with the extension host script.
As I would like to use Q in a Firefox add-on content script, I would like to know whether a PR with a fix for this particular problem would likely to be merged?

**Comment by CarlosCuevas** [comment]
Experiencing the same issue.  Will this merged anytime soon?

**Comment by kriskowal** [comment]
Please review #690
