### ISSUE TITLE
Unhandled rejection tracking global hook

### ISSUE THREAD

**Issue by benjamingr** [kriskowal/q#637]
Hey, I'd love it if you look at : https://gist.github.com/benjamingr/0237932cee84712951a2 for an unhandled rejection tracking hook.

**Comment by benjamingr** [comment]
Anyone?

**Comment by benjamingr** [comment]
Would a pull request at least on the v1 branch at least be entertained?

**Comment by benjamingr** [comment]
@kriskowal @domenic

**Comment by benjamingr** [comment]
Going to continue this at https://github.com/kriskowal/q/issues/637

**Comment by kriskowal** [comment]
My apologies for not responding. My notifications have been going to spam for a while and I’ve just noticed.

**Comment by benjamingr** [comment]
@kriskowal you're alive! :D

I've started a PR with Domenic's blessing to implement this now at the PR linked above - we discussed it a little and there is a done/todo list (rather minor).

What do you think?

**Comment by kriskowal** [comment]
Replied on linkèd PR.

**Comment by benjamingr** [comment]
Thanks - it's really nice to hear from you again!
