### ISSUE TITLE
Start checking in q.min.js

### ISSUE THREAD

**Issue by danielflower** [kriskowal/q#641]
For cases where projects can't or don't want to minify third party dependencies it's really useful to have a (tested) minified version checked in.

Would be great if the minified version could make a come back because as it stands we are stuck on 0.9.6

Great library btw

**Comment by kriskowal** [comment]
Keeping q.min.js in sync was more pain than it’s worth. I recognize that this would be convenient, but it encourages an anti-pattern. You should be bundling and minifying the bundles. If you don’t need to bundle, you almost certainly don’t need to minify.

**Comment by kriskowal** [comment]
And thank you. I appreciate the feedback and if it turns out you’re one of many, I always take a ticket as a sign.
