### ISSUE TITLE
Prerelease semver for experimental v2

### ISSUE THREAD

**Issue by mike-spainhower** [kriskowal/q#644]
Would it be possible to use prerelease versions for the v2 release train, which I understand will be completely experimental (https://github.com/kriskowal/q/issues/484)?

I realize that:
* This is kind of a PITA
* `npm` uses `dist-tags` to indicate latest stable

However, not using prerelease versions affects some other tools that strictly apply semver rules to the `versions` array of the npm package (e.g., https://bitbucket.org/versioneye/versioneye/issue/14/npm-use-dist-tags-for-actual-latest).   While this is only a mild annoyance with this particular tool, I can imagine that are others with more grave consequences.

Thanks for considering.

**Comment by kriskowal** [comment]
There are releases of v2 published to npm. Use npm install q@2 to get the latest release of the v2 branch. Also, expect breaking changes on patch releases. v2 is far from final. The same applies to many v2 branches of various projects I contribute to.

**Comment by mike-spainhower** [comment]
Yes, but it is kind of a bummer to break semver so completely.  Is it unacceptable to use e.g., 

```js
semver.inc('2.0.0-unstable.0', 'pre', 'unstable')
// 2.0.0 -> 2.0.0-unstable.0
// 2.0.1 -> 2.0.0-unstable.1
// 2.0.2 -> 2.0.0-unstable.2
// 2.0.3 -> 2.0.0-unstable.3
```

or

```js
semver.inc('2.0.0-unstable', 'prepatch', 'unstable')
// 2.0.0 -> 2.0.0-unstable.0
// 2.0.1 -> 2.0.1-unstable.0
// 2.0.2 -> 2.0.2-unstable.0
// 2.0.3 -> 2.0.3-unstable.0
```

**Comment by kriskowal** [comment]
Thank you for the ideas. I will think about it.

However, perhaps you should wait for the smoke to clear. I intend to announce a v2 release from which semver will be reinstated when it would be appropriate to start migrating dependees. The state of Q at present is so very experimental that you are likely to thrash needlessly on interface changes.

**Comment by reiz** [comment]
+1
