### ISSUE TITLE
Reseting a promise?

### ISSUE THREAD

**Issue by dtheodor** [kriskowal/q#657]
I've come across the need to be able to **reset** a promise. That is, if the promise is resolved, I want to mark the promise as unresolved, then re-trigger the original call that created that promise, and have this re-trigger all the chain of `then()`s that are attached to it.

It looks like promises are a one time object, and once resolved they get rid of all the attached callbacks and stay resolved forever. So the most obvious way to re-trigger the behavior is to throw away the old promise, create a new one, and attach all the `then()`s again. However this does not work when you have multiple modules that use the promise to attach additional `then()`s on it. Since the module where the promise is created has no knowledge of how many and how long are the then chains that have been attached, it cannot re-attach everything by itself.

This need has occurred in client-side applications where the promise objects are shared around across multiple modules that make use of the fetched data, often attaching `then()` functions that do some further transformation. It would be very useful if I could persist a single promise object in memory for a long time, and be able to reset() it at the data layer without having to write additional code for all clients of that data layer so that they re-trigger (or re-attach) the `then()`s to a new promise everytime the data is reloaded.

**Comment by Havvy** [comment]
You're fundamentally failing to understand how promises work. You're basically looking at a screw and asking for it to be changed into a Hammer because you tried to screw in a nail.

Promises will never be resettable. That violates one the invariants - that a promise is only resolved once.

What you are describing sounds to me like you want to create a pipeline, probably by using a Stream of some sort. Node.js/io.js has a Stream based on an Event Emitter, and it should work for what you want. I've yet to see an abstraction for pipelines in a similar vein of Promises being an abstraction for an asynchronous return value. The Stream code is itself "pure", and there are other Stream implementations too, for client side code. Plus browserify.

**Comment by kriskowal** [comment]
@dtheodor I believe what you are looking for is a Signal. I wrote up a long essay about finding the right tool for the job which might be insightful. https://github.com/kriskowal/gtor

@havvy Thanks for your feedback. I find that people feel more welcome if you open by explaining how you understand their motivation.

**Comment by Havvy** [comment]
Yeah, I'm not always very good at putting sympathy first. It's my natural state, but I forget that it's not visible to others. Your link is interesting, and I'm going to read it.

**Comment by dtheodor** [comment]
Hey thanks for the feedback.

I had looked both at signals and reactive libraries (streams). The thing is that the Promise API is very close to what I need, because it combines

1. chaining of post-processing (reactive does this too, and better)
2. information about whether a request is ongoing (unresolved promise). I could not find any concept of this in a reactive library (maybe I did not look good enough)
3. the API itself is exactly the API I need to consume, unlike signals or streams where more work needs to be done

I know my use-case can be implemented with signals, which I did.

However I opened the issue to ask why can a promise not being reset (and in case I missed the hidden reset API somewhere). Is this an argument against mutability?

None of the following statements answer the *why*.

> You're fundamentally failing to understand how promises work. You're basically looking at a screw > and asking for it to be changed into a Hammer because you tried to screw in a nail.
> 
> Promises will never be resettable. That violates one the invariants - that a promise is only resolved > once.

**Comment by domenic** [comment]
A promise is like an async return value. I.e., synchronous functions return values, asynchronous functions return promises.

The caller of a synchronous function can't change the return value of that function. Similarly, the caller of an asynchronous function can't change the return value of that function, i.e., nobody can reset a promise.

**Comment by dtheodor** [comment]
Ok I can see that argument. You treat a promise as an immutable future value, while I wanted to use it more like an event to chain callbacks on.

**Comment by joepie91** [comment]
@dtheodor This may be useful for your usecase: http://highlandjs.org/

**Comment by kriskowal** [comment]
Thanks for the discussion.
