### ISSUE TITLE
When to make a function deferred

### ISSUE THREAD

**Issue by aadamsx** [kriskowal/q#663]
I have a few function calls to make to both my own custom functions and node.js fs style async functions.

if I'm making a call to a function like this:
```
do_something = function (input) {
  // assign variables, do other sync stuff 
}
```

and need the above to take place ```before``` this function:
```
do_something_else = function (input) {
  // assign variable, do other sync stuff
}
```

and ```then``` need to call a native node function:
```
writeData = function (obj) {
  var deferred = Q.defer();
  fs.writeFile(obj.file, obj.datas, function (err, result) {
    if (err) deferred.reject(err);
    else deferred.resolve('write data completed');
  });
  return deferred.promise;
}
```

and ```finally``` need the above to take place ```before``` this function:
```
do_something_last = function (input) {
  // assign variable, do other sync stuff
}
```

Is the 'right' thing to do here, to make all my functions 'deferred' or promise aware so I can make sure that they are called in sequence and in the correct order?

like so:
```
do_something(variable)
.then(do_something_else)
.then(writeData)
.then(do_something_last)
.done();
```
or can I just do this instead and keep the ordering (sequencing)?  Like so:
```
var variable1 = 'test1.txt'
var variable2 = 'test2.txt'
var return_value = do_something(variable1);
var return_another_value = do_something_else(return_value);
writeData(return_another_value);
var final_value = do_something_last(variable2);
```

**Comment by aadamsx** [comment]
I've posted a SO question on this topic: http://stackoverflow.com/questions/28993673/when-to-make-a-function-deferred-using-promises

**Comment by bpq** [comment]
I've wondered about this myself. Quoting from the SO answer:

+ make synchronous functions synchronous - no need for promises
+ make all asynchronous functions always return a promise
+ use deferreds only at the lowest possible level for promisification

I think the right thing is to make all functions deferred like

```js
do_something(variable)
.then(do_something_else)
.then(writeData)
.then(do_something_last)
.done();
```

**Comment by kriskowal** [comment]
I hope that @bpq’s summary is satisfying. From our README, always either .done() or return a promise.
