### ISSUE TITLE
makeNodeResolver returns array of arguments instead of standard arguments

### ISSUE THREAD

**Issue by BerkeleyTrue** [kriskowal/q#665]
[this](https://github.com/kriskowal/q/blob/v1/q.js#L621) here will change the expect return of callbacks that return more then one result argument. 

For instance, dealing with a callback signature that has changed from `(err, conflicts`) to `(err, conflicts, cps)`. Because of this, now promise.then returns an array with conflicts and index 0 and cps at index 1 which is not intuitive and breaks code through no fault of its own.

Might I suggest changing that line to

`self.resolve.apply(self, array_slice(arguments, 1));`

I can submit a PR if this works for everyone.

see https://github.com/strongloop/loopback/issues/1223

**Comment by kriskowal** [comment]
This has been addressed in the v2 branch. This is a backward-incompatible change, so it can arrive no sooner than version 2, which is and will always be an opt-in upgrade. Version 2 also remains unstable until we have settled on what set of breaking changes we would like to make final.

My time lingering over the v2 trigger may have to come to an end soon.

**Comment by BerkeleyTrue** [comment]
Okay sweet. Looking forward to it. I will close this issue.
