### ISSUE TITLE
Release 1.2.0 doesn't have tag

### ISSUE THREAD

**Issue by trothwell** [kriskowal/q#674]
### Issue
* Changes has 1.2.0: [CHANGES.md](https://github.com/kriskowal/q/blob/v1/CHANGES.md)

### Expected
* Releases should have a listing for v1.2.0 [/releases](https://github.com/kriskowal/q/releases)

### Actual
* Releases **doesn't** show v1.2.0 [/releases](https://github.com/kriskowal/q/releases)

**Comment by kriskowal** [comment]
Thanks. I’ll make sure the changes are pushed tonight.

**Comment by kriskowal** [comment]
pushed
