### ISSUE TITLE
q.all().then().then() switches from rejected to fulfilled

### ISSUE THREAD

**Issue by dmm9** [kriskowal/q#675]
**Using**
node v0.12.2
q@1.2.0

**Code**
```javascript
var q = require('q');
var fs = require('fs');

function ReadMyFiles() {
	return q.all([
		q.nfcall(fs.readFile,'file1.txt','utf8'),
		q.nfcall(fs.readFile,'fileee2.txt', 'utf8')  // fileee2.txt doesn't exist
	])
}

ReadMyFiles()
.then(
	function(data) {
		console.log('All files read!');
	},
	function(reason) {
		console.log('Some file could not be read. Reason: ');
		console.log(reason);
	}
)
.then(
	function(data) {
		console.log('Fulfilled!');
	},
	function(reason){
		console.log('Rejected');
	}
)
```

**Returns**
```console
Some file could not be read. Reason:
[Error]
Fulfilled!
```

**Expected**
```console
Some file could not be read. Reason:
[Error]
Rejected
```

**Comment by kriskowal** [comment]
This is expected behavior. Each call to .then creates a new promise for the return value or thrown exception of the rejected or fulfilled callback. Since you return undefined in both cases for the handlers of the first promise, the second promise is fulfilled with undefined.

**Comment by kriskowal** [comment]
Addendum: If you wish the exception to propagate to the second handler, rethrow.

```javascript
var q = require('q');
var fs = require('fs');

function ReadMyFiles() {
	return q.all([
		q.nfcall(fs.readFile,'file1.txt','utf8'),
		q.nfcall(fs.readFile,'fileee2.txt', 'utf8')  // fileee2.txt doesn't exist
	])
}

ReadMyFiles()
.then(
	function(data) {
		console.log('All files read!');
	},
	function(reason) {
		console.log('Some file could not be read. Reason: ');
		console.log(reason);
                throw reason; // XXXXXXX
	}
)
.then(
	function(data) {
		console.log('Fulfilled!');
	},
	function(reason){
		console.log('Rejected');
	}
)
```

**Comment by dmm9** [comment]
I thought that rule was of the kind promise2 = ReadMyFiles.
However, from [https://promisesaplus.com/]:

2.2.6 'then' may be called multiple times on the same promise.
2.2.6.1 If/when promise is fulfilled, all respective onFulfilled callbacks must execute in the order of their originating calls to then.
2.2.6.2 If/when promise is rejected, all respective onRejected callbacks must execute in the order of their originating calls to then.

**Comment by kriskowal** [comment]
2.2.6 refers to parallel, not series, usage of `then`. Consider:

```js
var files = ReadMyFiles()

files.then(
    function(data) {
        console.log('All files read!');
    },
    function(reason) {
        console.log('Some file could not be read. Reason: ');
        console.log(reason);
    }
)

files.then(
    function(data) {
        console.log('Fulfilled!');
    },
    function(reason){
        console.log('Rejected');
    }
)
```

**Comment by dmm9** [comment]
Wheather synchronous or asynchronous, **all respective onRejected callbacks must execute**, and furthermore **must execute in the order of their originating calls to then** (per series nature of the promise.then().then() structure).
In my snippet not all the onRejected callbacks are executed. The promise 'ReadMyFiles' is clearly rejected and it executes an onFulfilled callback.

**Comment by dmm9** [comment]
OK got it. I will explain it just in case someone gets to the same misunderstanding:

Each promise has ONLY ONE _then_. So in order to chain the _then_ operations (serialize the execution) it must be clear that _then_ returns a promise and consequently:
_promise.then().then()_ is the equivalent of _subpromise(promise.then()).then()_

So the first (and consecutive) promise.then() should 'throw' the error to keep the chain being rejected. Therefore, in order to serial-execute several commands when one promise has been rejected, this would be the recommended code:

```javascript
promise
.then(
    function(value) {
        /* onFulfilled operations here */
    },
    function(reason) {
        /* onRejected operations here */
        throw reason; // to keep the Rejected status
)
.then (
    function(value) { 
        /* onFulfilled operations here */
    },
    function(reason) {
        /* onRejected operations here */
        throw reason; // to keep the Rejected status
)
...
```

Sorry for posting as an issue. But it wasn't clear in any part of the documentation.

**Comment by kriskowal** [comment]
Unhelpful docs are a bug. Please let us know what we can do to make the Q README clearer. This is the relevant section:

https://github.com/kriskowal/q#propagation
