### ISSUE TITLE
Q.js has no option to non populate the global namespace

### ISSUE THREAD

**Issue by augusto-altman** [kriskowal/q#677]
I couldn't find a way to tell Q to not populate the browser's global namespace (window) with the Q function. I was looking for something similar to the [the jQuery noConflict feature](https://api.jquery.com/jquery.noconflict/).

**Comment by domenic** [comment]
You could use browserify, or you could do this:

```js
var Q = window.Q;
delete window.Q;
```

**Comment by augusto-altman** [comment]
Regarding your first approach: In my project we are already using AMD (requirejs) and change everything to Browserify (commonjs) is just not possible.

Regarding your second approach: I'm making a library, so I don't know when my code is going to be loaded. So what would happen If the developer loads more scripts before my library and one of these has defined a window.Q variable? I wouldn't be able to just delete window.Q because I would break his application.

**Comment by domenic** [comment]
Deleting window.$ is exactly what jQuery.no conflict does so I don't really understand what you want.

**Comment by augusto-altman** [comment]
No it doesn't, here it is a chunk of code taken from the bottom of the jQuery bundle (non minified)

```JavaScript
//.................jQuery code......................
//.................jQuery code......................
//.................jQuery code......................
var
	// Map over jQuery in case of overwrite
	_jQuery = window.jQuery,

	// Map over the $ in case of overwrite
	_$ = window.$;

jQuery.noConflict = function( deep ) {
	if ( window.$ === jQuery ) {
		window.$ = _$;
	}

	if ( deep && window.jQuery === jQuery ) {
		window.jQuery = _jQuery;
	}

	return jQuery;
};

// Expose jQuery and $ identifiers, even in AMD
// (#7102#comment:10, https://github.com/jquery/jquery/pull/557)
// and CommonJS for browser emulators (#13566)
if ( typeof noGlobal === strundefined ) {
	window.jQuery = window.$ = jQuery;
}
```

As you can see, before exposing the $ and jQuery variables to the global namespace (window object) they check if it was a previous value in window.$ and window.jQuery and (if any) saves them into an internal cache. When you execute the noConflict it takes those cached values into account and not simply delete the global variable.

**Comment by augusto-altman** [comment]
You can check that in their [repo](https://github.com/jquery/jquery/blob/master/src/exports/global.js) if you want to.

**Comment by kriskowal** [comment]
I would entertain a PR for this feature in the v1 branch, but feel this feature is highly antiquated in a world with module systems.

**Comment by augusto-altman** [comment]
It's true, it's a highly antiquated feature. In a world with module systems it's as antiquated as exposing Q in the window object. The thing is, if you are polluting the global namespace, then you should provide a way to de-pollute it, because it could be a poor guy like me out there, that have to work with legacy code and have to avoid namespace conflicts.

Thank you very much for taking the time to fix this.
