### ISSUE TITLE
Unexpected behavior with Object.defineProperty

### ISSUE THREAD

**Issue by WishCow** [kriskowal/q#679]
If I have an object, that has properties defined with `Object.defineProperty`, the properties (or more like, the getters of the properties) cannot be used in promise chains.

Example:

```js
var q = require('q');
var Mail = function() {};

Object.defineProperty(Mail.prototype, 'attachments', {
    get: function() {
        return q.resolve(['Attachment #1']);
    }
});

var mail = new Mail();

q.resolve()
    .then(function() {
        return 'First then';
    })
    .then(mail.attachments)
    .done(function(result) {
        console.log(result);
    });
```

The script above is going to output `First then`, instead of the expected `['Attachment #1']`.

Is this the expected behavior? Are you not supposed to use descriptors as callbacks for promises? Or is there some assumption that Q makes when it receives the descriptor, that makes it trip up in cases like this?

**Comment by domenic** [comment]
Let's translate that code: substitute the return value of the getter where you put `mail.attachments`. The result is:

```js
q.resolve()
    .then(function() {
        return 'First then';
    })
    .then(q.resolve(['Attachment #1']))
    .done(function(result) {
        console.log(result);
    });
```

So you are passing a promise to `.then`, which does not work, since `.then` only accepts functions.
