### ISSUE TITLE
Pass result of promise to another deferred

### ISSUE THREAD

**Issue by aramk** [kriskowal/q#680]
Say I have this situation:
```
function test() {
  return Q.resolve(123);
}

function test2() {
  var df = Q.defer();
  setTimeout(function() {
    test().then(df.resolve, df.reject);
  }, 1000);
  return df.promise;
}

test2().then(function() {
  console.log(arguments);
}).done();
```
The main part I want to highlight is `test().then(df.resolve, df.reject)`. This pattern is used throughout my code in situations where I need to invoke a method which returns a promise but cannot do so synchronously, so I need to set up another promise and pass the result to this one so that I can return a promise synchronously from my method. Is there a method for passing all results across from a promise to a deferred object? All events like done, fail, fin, progress etc. would need to be passed but this would be tedious to repeat throughout the codebase. Am I missing something fundamental or is such a method useful?

**Comment by domenic** [comment]
That code will indeed pass all relevant information. Can you give a test showing otherwise?

Equivalent code would be `df.resolve(test())`.

**Comment by aramk** [comment]
Thanks @domenic that works great. My question was whether it's possible to reduce the need for using .then() each time and just linking the result of one promise to another.

**Comment by domenic** [comment]
Well your best scenario is if you are using promise functions instead of adapting callback code like setTimeout. For example if you use Q.delay then you can just do

```js
function test() {
  return Q.resolve(123);
}

function test2() {
  return Q.delay(1000).then(test);
}

test2().then(function () {
  console.log(arguments);
}).done();
```

**Comment by aramk** [comment]
Yeah that was just an example. My main confusion was whether I could bind the outcome of one promise to that of another, and `df.resolve(test())` does exactly that. Thanks, this will cleanup a lot of code!
