### ISSUE TITLE
Is there a way to throw immediately by crashing the application rather than propagating a rejected promise and having to reveal it using `done`?

### ISSUE THREAD

**Issue by aleksey-bykov** [kriskowal/q#684]

**Comment by kriskowal** [comment]
```js
process.nextTick(function (error) {
    throw error;
})
```

However, that is what `done()` effectively does.

Some folks have wondered whether it would be possible to automatically distinguish operational errors from programmer errors, throwing the latter and rejecting the former. Distinguishing errors is beyond the scope of Q, but it certainly is possible to:

```js
.catch(function (error) {
    if (!isOperational(error) {
        process.nextTick(function () {
            throw error;
        });
    }
    throw error;
})
```
