### ISSUE TITLE
npm update on debian wheezy installs the wrong version of q

### ISSUE THREAD

**Issue by kamijoutouma** [kriskowal/q#692]
http://pastebin.com/qtHmvSdY
http://pastebin.com/naUjfaVE

i updated q with npm update on my debian wheezy server and when i went to run some stuff i got all kinds of deprecation errors from q

when i did npm install q --force the errors went away 

when i did npm update the errors came back

touma@Index:~/test$ npm update
npm http GET https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/asap
npm http GET https://registry.npmjs.org/pop-iterate
npm http GET https://registry.npmjs.org/weak-map
npm http 304 https://registry.npmjs.org/asap
npm http 304 https://registry.npmjs.org/weak-map
npm http 304 https://registry.npmjs.org/pop-iterate
q@2.0.3 node_modules/q
├── pop-iterate@1.0.1
├── weak-map@1.0.5
└── asap@2.0.3

@kriskowal

**Comment by kriskowal** [comment]
I’m not sure how you ended up with q@2. q@1.4.0 is latest in npm and you have to explicitly opt-in for version 2. There is some chance that version 2 got trapped in your package.json or shirnkwrap. Otherwise, I am unable to reproduce the problem locally.
