### ISSUE TITLE
Should fix licenses

### ISSUE THREAD

**Issue by domenic** [kriskowal/q#694]
Recently npm deprecated the object-literal license format in favor of SPDX license specifiers. See https://docs.npmjs.com/files/package.json#license

We should update both 1.x and 2.x branches with just "MIT" instead of the current object literal.

Spotted via http://npm1k.org/

**Comment by domenic** [comment]
Ah I see #693 takes care of this for the 1.x branch.

**Comment by kriskowal** [comment]
Landed for v1 and I’ve got a fix for v2 in my working copy. Closing this to get it out of the inbox.

**Comment by stramel** [comment]
@kriskowal Not seeing this in v2 still. Just curious if this is still a valid bug?
