### ISSUE TITLE
Q.all -> sequential in debug mode

### ISSUE THREAD

**Issue by cadorn** [kriskowal/q#695]
I find it very useful to see my code run more sequential when working and debugging.

I would like to be able to set a debug environment variable like `Q_DEBUG` that switches the underlying implementation of `Q.all()` to execute all promises sequentially.

**Comment by kriskowal** [comment]
`Q.all` does not have the ability to limit concurrency. It receives an array of input promises for work that has already started. Q-IO v2 provides a `Reader` that implements `map` with a concurrency limit that you adjust parametrically.

```js
new Reader(iterable)
.map(function (value) {
    // return promise
}, null, config.development ? 1 : 100)
.all()
```

**Comment by cadorn** [comment]
Ah of course. Too many abstractions in my head tonight ;)
