### ISSUE TITLE
resolve value is undefined when chaining then method

### ISSUE THREAD

**Issue by schmeic** [kriskowal/q#702]
I am getting an undefined value in my onFulFilled method when chaining the then method. Here's a simple example:

	var deferred = Q.defer();

	var onFulfilled = function(value) { console.log("value: " + value); };
	
	deferred.promise.then(onFulfilled).then(onFulfilled);
        // value: 9
        // value: undefined
	
	deferred.promise.then(onFulfilled);
	deferred.promise.then(onFulfilled);
        // value: 9
        // value: 9
	
	deferred.resolve(9);

Is this the expected behavior?

**Comment by kriskowal** [comment]
Yes. then() returns a promise for the value returned, excpetion thrown, or promise resolved by onFulfilled or onRejected. Chaining is different than branching.

**Comment by schmeic** [comment]
Ok, got it.  Thank you for the quick response.
