### ISSUE TITLE
Promise seems not a Monad

### ISSUE THREAD

**Issue by HaskellZhangSong** [kriskowal/q#721]
var Q = require('q')

	var async = function(e){return Q(e)}

	function test(){
		var promise = Q(new Object)
		return promise.then(function(ob){
			ob.haha = 100
			async(ob.haha).then(function(num){
				ob.aha = num
				return ob
			})
		})
	}

	test().then(function(a){console.log(e)})

Is my code wrong? Nothing is printed
It seems that then should be bind function of a Monad, however, the function test doesn't return anything. I suspect that the implementation of Q promise is not quite complete.

**Comment by kriskowal** [comment]
Change last line to have `.done()` on the end, which will cause exceptions to surface. There is a reference error in your console.log(e) expression. There is also a missing return in your test.

**Comment by HaskellZhangSong** [comment]
Thanks, worked. ~~
