### ISSUE TITLE
Question - Deferred Anti Pattern

### ISSUE THREAD

**Issue by rudijs** [kriskowal/q#726]
Hi,

I think I might be using the "Deferred Anti Pattern", I'm not sure so would like to ask real quick.

I'd like to use the nodejs memcached node module but return a promise (it's nodejs callback style).

I did initially start with q.nfbind but got errors `TypeError: Cannot read property 'namespace' of undefined`

Here's the code I'm experimenting with (runs from the command line), does it look correct?

Thanks!

```
'use strict';

var Memcached = require('memcached'),
  Q = require('q');

var memcached = new Memcached('192.168.33.10:11211');

var memcachedGet = function (memcached, key) {

  var q = Q.defer();

  memcached.get('foo', function (err, data) {
    if (err) {
      q.reject(err);
    }
    else if (!data) {
      q.reject('no data');
    }
    else {
      q.resolve(data);
    }
  });

  return q.promise;

};

memcachedGet(memcached, 'foo')
  .then(function (res) {
    console.log('res', res);
  })
  .catch(function (err) {
    console.log('err', err);
  })
  .finally(function() {
    // commandline script so end connection here.
    memcached.end();
  });
```

**Comment by domenic** [comment]
Yes, this is the antipattern in action. Instead you should use

```js
function memcachedGet(key) {
  return Q.ninvoke(memcached, "get", key).then(function (data) {
    if (!data) {
      throw new Error("no data");
    }
  });
}
```

or similar.

Also, in the future you may find StackOverflow a better outlet for these questions, as this is not a bug with Q.
