### ISSUE TITLE
`Q.all()` never fulfilled immediately

### ISSUE THREAD

**Issue by nknapp** [kriskowal/q#727]
Is it intentional, that `Q.isFulfilled(Q.all([2,2])) === false`? 
I would have thought that as long as the input of Q.all() contains no promises 
or only fulfilled promises, the result of Q.all() should also be fulfilled.
I'm having some problems that originate from always being put into the next eventloop-cycle when doing `Q.all()`

**Comment by kriskowal** [comment]
@nknapp We did intentionally omit synchronous state queries from Q for a long while and left them only for perf optimizations and debugging reasons. We do intentionally call handlers asynchronously, regardless of the state of the promise. If you need an order guarantee, `then` is there to ensure it.

We don’t intentionally return false for this specific case, but it is an emergent behavior. Creating a special case would probably not be worthwhile, but I would certainly consider a change if it is simple.

**Comment by nknapp** [comment]
Thanks for the quick reply. 
It would have been helpful for me if `Q.all([2,2]).then(fn)` would have called `fn` immediately, because I would then have been able to use temporary data-structures that are cleaned at the end of the calling function.
But I have now [found the part in the docs now](https://github.com/kriskowal/q#tutorial) and [in the Promise A+ spec](https://promisesaplus.com/#point-34) that explicitly prohibit this behaviour and I can see why. So I'm closing this issue.
