### ISSUE TITLE
Brunch build error

### ISSUE THREAD

**Issue by bagbee** [kriskowal/q#730]
Hey, 

I use http://brunch.io for building my scripts, but I heve an error:

```
error: [Error: Component JSON file "/home/andrei/GoogleDrive/Projects/www/presenter/bower_components/q/.bower.json" must have `main` property. See https://github.com/paulmillr/read-components#README]
```

so, can you add  `main` property to bower.json?

Thanks.

**Comment by RiCoTeRoX** [comment]
+1, 
please we need that !!!

into the 1.x version please

**Comment by kriskowal** [comment]
The Q project does not directly support Bower. Anyone who is providing support for Q in Bower, please let these folks know where they can go to get this issue addressed.
