### ISSUE TITLE
Promise.catch eats errors

### ISSUE THREAD

**Issue by ccorcos** [kriskowal/q#745]
I've been struggling with a test for some time now and after putting logs everywhere, it appears I had an error in `.catch` that just silently gets gobbled up by the promise. Check out this example:

```js
let x = Q.defer()
x.promise.catch(function(error) {
  a = b // this error will silently fail
  console.log('error', error) // this line will never run
})
x.reject('something')
```

**Comment by kriskowal** [comment]
terminate your promise chain with `.done()`.

**Comment by ccorcos** [comment]
interesting... thanks for the quick response
