### ISSUE TITLE
sync function

### ISSUE THREAD

**Issue by alfredopacino** [kriskowal/q#759]
Hi, this is my promise example (express+mongoose)
Maybe someone can explain me why in console I see "New post added" *before* "User found" and "User not found.."?

    app.post('/api/community/posts', function(req,res){

    q.fcall(function(){
         var arr=[];

        req.body.postedBy.forEach(function(el){
            com_user.findById(el._id, function (err, user) {
                if (user) {
                    console.log("User found!" + user.name);
                    arr.push(user._id);
                } else {
                    var com_user1 = new com_user({
                        name: el.label,
                        age: 20
                    });
                    com_user1.save(function (err, newuser) {
                        if (err)
                            console.log(err)
                        else {
                            console.log('User not found and just added!');
                            console.log(newuser)
                            arr.push(mongoose.Types.ObjectId(newuser._id));
                        }
                    })
                }
            })
        })
        return arr
    })
        .then(function (arr) {
            console.log('arr')
            console.log(arr)

            var com_post1 = new com_post({
                content: req.body.content,
                postedBy: arr,

            });
            com_post1.save(function (err) {
                if (!err) {
                    console.log("New post added!");
                    res.json({"New post added! ": req.body.content});
                }
                else {
                    res.json({"Error adding post": 'error'});
                    error(err)
                }

            })
        })
        .catch(function (err) {
          console.log(err)
        })

**Comment by benjamingr** [comment]
Promises work by `return` value and you're not `return`ing anything from your `then` chains.

Promises don't know how to wait for things automatically - the way to "wait" for previous actions is to `return` the promise they create from the `then` handler:

```js
Q().then(() => {
    return Q.delay(1000);
}).then(() => {
    // this only executes after 1000ms because the previous `then` handler `return`d a promise
});
```
