### ISSUE TITLE
Automatically propagate all exceptions

### ISSUE THREAD

**Issue by seiyria** [kriskowal/q#763]
I'm looking for a way to automatically propagate exceptions in all of my promise code. Having to have a `.catch` everywhere just to _see_ an exception is cumbersome - it feels like I'm try/catching all of my code. For example, I spent about 10 minutes the other day trying to figure out where an error came from... I forgot to `import` a library I was using. Normally, I would see that error right away because that's a pretty significant error, especially in strict mode.

Probably, this would be some sort of global or environment setting so I don't have to remember to do it every time I make a promise. I don't know if this is default behavior already, but in the case where a promise is hit by an exception, it might be wise to auto-reject that promise as well so there isn't a dangling promise.

If it's difficult to do that, even just (having an option to) saying "hey, I got an error, here's the stack trace" would be nice.

**Comment by Juljan** [comment]
I would also appreciate such feature. 

In my code, I call `.done();` on all promises, this makes stacktraces visible without polluting the code like the try-catch solution.

**Comment by benjamingr** [comment]
@seiyria In Node - you can add a `process.on("unhandledRejection",` handler and see the result. 

I don't think at this point Q can change the default for unhandled rejection tracking to be like bluebird (log by default).

**Comment by seiyria** [comment]
I don't see why it can't. Maybe it'd require a major version change, but surely it's possible. That said, I'm not super invested in this anymore - I dropped q in favor of ES6 promises due to concerns over #731.

**Comment by benjamingr** [comment]
@seiyria ok, for what it's worth you can keep using Q's API and get better than native performance with https://github.com/petkaantonov/bluebird-q

Closing then.
