### ISSUE TITLE
Missing error handler on `socket`. TypeError: Cannot call method 'then' of undefined whe try to make a promise with postgres query result

### ISSUE THREAD

**Issue by AnD010** [kriskowal/q#766]
Hi!
I´m rookie with nodejs and with promises, I installed Q.js with npm :  
 npm install q
I´m try yo make a promise when I made a query to postgres, this is my code...

   ```
socket.on('Operation', function (data) {
....... 
getElementInPostgres(makeQuery)
    .then(function (name) {
          console.log("promiseeee then");
          .......blablabla
  })
    .fail(function (err) {
      console.log("promiseeee error");

    });
.............
function getElementInPostgres(makeQuery){
  console.log("entro getElementInPostgres");
  var deferred = Q.defer();
  client.query(
                  makeQuery,
                  function(err, result) {
                    if (err) {
                       console.log("NO getElementInPostgres");
                      console.log(err);
                      deferred.reject(err);
                    } else {
                       console.log("ok getElementInPostgres");
                     console.log(result);
                     deferred.resolve(result);
                    }
                    return deferred.promise;
                });
}
```
But my code crash 
Missing error handler on `socket`.
TypeError: Cannot call method 'then' of undefined.....

I was looking at examples and do not see anything different in my code ...

Thanks !

**Comment by ForbesLindesay** [comment]
You should return `deferred.promise` outside the `client.query` callback (I.e. Swap it the line after it)

**Comment by benjamingr** [comment]
Also, as a tip - always convert your API to promises at the _lowest level possible_ - convert `.query` itself.

**Comment by AnD010** [comment]
Thanks so match @ForbesLindesay , I made a stupid fail.... change outside to client deferred and work fine now....I'm so rookie with node...
@benjamingr , you have absolutely right, I will chek how make with .query  conexion with postgres db.
This is my first time with node...Always, I only make android and Ios code(front)... now, I make backend too.
thanks to both
