### ISSUE TITLE
Importing/requiring q module works with both small and caps

### ISSUE THREAD

**Issue by girishsortur** [kriskowal/q#779]
I came across this strange issue when i was working on a sample app locally. Below are two statements -

`var q = require('q');`

`var q = require('Q');`

Surprisingly i don't get any error when i use the second statement locally in my machine, which indeed should have thrown me the error that the node module is not found. But it doesn't. However, the same code throws error when i try to use it cloud env.

I have `├ q@1.4.1` with node v5.2.0

**Comment by vilic** [comment]
The file systems of Windows and OS X (by default) are not case sensitive, I don't see why this is unexpected.

**Comment by girishsortur** [comment]
@vilic I was working on an app in my local machine (OSX) and i didn't get any error with this. However, when i tried to push it to IBM Bluemix (which is linux based cloud env), it was throwing an error stating -

`ERR Error: Cannot find module 'Q'`

So shouldn't it be case sensitive and uniform across platforms? Thanks!

**Comment by vilic** [comment]
@girishsortur Actually this has nothing to do with Q, if you would want more context, please refer to Node.js issues like https://github.com/nodejs/node-v0.x-archive/issues/6000
