### ISSUE TITLE
asynchronous for each

### ISSUE THREAD

**Issue by darkdragon-001** [kriskowal/q#780]
I find myself doing the following over and over again:

```
var items = [1,2,3,4]; // some array
var itemsP = items.map(function(item){
  // do some blocking operation with item which returns a promise
  return item;
});
return q.all(itemsP);
```

Maybe it makes sense do define a function `Q.each` or `Q.map` as follows

```
Q.each = function(arr, func) {
  return q.all(arr.map(func));
}
```

**Comment by benjamingr** [comment]
I think the API surface is pretty frozen at this point, but you can either use a library with these helpers like https://github.com/petkaantonov/bluebird or implement them yourself (like you did above)
