### ISSUE TITLE
getting full errors stacks using Q.allSettled?

### ISSUE THREAD

**Issue by ebarault** [kriskowal/q#784]
I'm using this piece of code:
```
return Q.allSettled([
                somePromise,
                someOtherPromise
            ])
            .then(function (results) {
                results.forEach(function (result) {
                    if (result.state !== 'fulfilled') {
                        console.log(result.reason);
                    }
                });
            });
```

which is fine to handle silently errors from my array of promises.
Though, `result.reason` only gives the error message, which is not convenient.

Is there a way to get the full error stack bubbled by one of the rejected promises?
thx,

**Comment by kriskowal** [comment]
result.reason should be an Error instance. as with throw, the language permits you to throw other things, but in practice, they should always be Error instances. This problem must be solved in the provider of somePromise or someOtherPromise.
