### ISSUE TITLE
Series with Q

### ISSUE THREAD

**Issue by jdnichollsc** [kriskowal/q#788]
Hi guys,

What is the correct way to use series?

Thanks in advance, Nicholls

**Comment by sth** [comment]
It's not clear what you are trying to do. What "series" are you talking abbut and what are you trying to do with them?

**Comment by jdnichollsc** [comment]
For example: http://caolan.github.io/async/docs.html#.series

To avoid the following code:

```javascript
var users = [user1, user2, user3];
var result = Q();
users.forEach(function (user) {
  result = result.then(function(){
    return createUser(user);
  });
});
```

Regards, Nicholls

**Comment by cdhowie** [comment]
If you don't need the results from the `createUser()` calls, this pattern does the trick:

```js
users.map(user => () => createUser(user)).reduce(Q.when, Q())
```
