### ISSUE TITLE
Read Format in Netbeans

### ISSUE THREAD

**Issue by zelin** [kriskowal/q#790]
I have a working project based on socket.io, node.js using Q Promise, however the netbeans isn't recognising any format

A simple example 
<img width="1090" alt="screen shot 2016-09-27 at 10 17 34 am" src="https://cloud.githubusercontent.com/assets/1249435/18861038/ac508c96-849b-11e6-82d1-60ba6dda45c8.png">

Is there any plugin available that will help me resolve these syntax issues and make the project run directly from netbeans?

**Comment by cdhowie** [comment]
It looks like the editor doesn't understand ES6 syntax like arrow functions.  Have you tried using only ES5 syntax?  (Replace `(err) =>` with `function (err)` in this case.)
