### ISSUE TITLE
promise.delay not working as expected for rejected promises

### ISSUE THREAD

**Issue by lucasprus** [kriskowal/q#801]
https://github.com/kriskowal/q/wiki/API-Reference#promisedelayms

Compare: 

`Q(10).delay(5000).then(console.log);`
Works as expected and logs after 5 sec.

`Q.reject(10).delay(5000).catch(console.log);`
Logs immediately without delay. Why?

**Comment by benjamingr** [comment]
Because the promise is rejected. This is like the following sync code:

```js
try { 
  throw Error();
  sleep(5000) 
} catch (ex) { console.log(ex); 
```

It's just how control flow works in programming.

**Comment by lucasprus** [comment]
Thanks for immediate response.

So the API documentation isn't right then?
> Returns a promise that will have the same result as promise, but will only be fulfilled or rejected after at least ms milliseconds have passed.

**Comment by benjamingr** [comment]
That is correct, the docs need to be updated - feel free to submit a PR (removing the "at least" part).

**Comment by lucasprus** [comment]
It's the "or rejected" part that needs to be removed really.

I just updated wiki:

https://github.com/kriskowal/q/wiki/API-Reference#promisedelayms

Also added an extra sentence there.

By the way, I don't think I should be allowed to do this? I don't have any special permissions to this project.

https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by benjamingr** [comment]
> I just updated wiki:

Thanks.

> By the way, I don't think I should be allowed to do this?

So far, I've been a member of several projects that allowed this and I've never seen it abused. While it's possible to set permissions it is often not necessary and the good will of users helps improve documentation.
