### ISSUE TITLE
Make master the primary branch again.

### ISSUE THREAD

**Issue by kriskowal** [kriskowal/q#804]
I’m leaving q v2 behind as an ambition from the past I don’t intend to further. I think it makes sense make v1 the master branch again. Any objections?

**Comment by jbunton-atlassian** [comment]
+1

I think it'd be great to do an npm release of v1 as well.

**Comment by kriskowal** [comment]
Yeah, published v1.5.0 a few hours ago.

**Comment by kriskowal** [comment]
So it is done. `master` is the primary branch.

**Comment by jbunton-atlassian** [comment]
:)
