### ISSUE TITLE
Forget to resolve.

### ISSUE THREAD

**Issue by hifall** [kriskowal/q#809]
If for some reason, one forgets to resolve a promise that is last chained (call it "tail-promise" for convenience's sake) using then method, what are the consequences? Does it cause resource leak of any sort? And if so, is the effect cumulative?

We are currently using q inside a non-trivial node.js-based server, and we use promises quite extensively. Some of the promises are long-chained and nested. We have found some of the tail-promises to not call resolve as expected, from time to time. Although the server appears to function properly, I'd like to know if this has some bad effects.

Thanks!

**Comment by benjamingr** [comment]
@hifall this should be fine.

**Comment by hifall** [comment]
What actually happens? Care to add some explanation on it?
