### ISSUE TITLE
Rejecting with no value using Q.any()

### ISSUE THREAD

**Issue by ivanetchart** [kriskowal/q#812]
Let's say I'm doing:

```
function returningPromise() {
   return new Promise((resolve, reject) => {
      ... at some point ...
      reject();
   })
}
```

then:

```
Q.any([returningPromise()]).catch(() => something())
```

something() will never be called, because Q.any is never going to be rejected, causing an odd behavior. I submitted a PR for you to check. I think it should not assume that an exception is going to be passed into a Promise rejection, and let the client to decide that (even if it's not a good practice).

Please let me know your thoughts,

Thanks

**Comment by kriskowal** [comment]
The correct behavior in principle would be to propagate an "all rejected" exception if all of the inputs are rejected. I’ll leave some space for my fellow maintainers to weigh in.

**Comment by jbunton-atlassian** [comment]
It looks like this was broken by me in c340b2d05241330674697705a5e4b00c7ac1443b. Previously q did propagate a generic 'all rejected' error. However this turns out to make debugging issues difficult.

@ivanetchart, I think your fix makes sense, I've added some minor feedback to your PR.
