### ISSUE TITLE
"require is not defined"

### ISSUE THREAD

**Issue by Spongman** [kriskowal/q#820]
the tutorial page states:

    A <script> tag (creating a Q global variable): ~2.5 KB minified and gzipped.

however, if you add the following to a blank html page:

    <script src="https://cdnjs.cloudflare.com/ajax/libs/q.js/2.0.3/q.js"></script>

you get the following error:

    require is not defined

there is NO mention of 'require' on the tutorial page.

**Comment by kriskowal** [comment]
Use the "latest" version in npm, which is the most recent release in the version 1 train. Version 1 does not depend on the presence of a CommonJS module system.
