### ISSUE TITLE
q.all inside q.all

### ISSUE THREAD

**Issue by elpaxdota** [kriskowal/q#821]
I have small problem. That's my code:
```
Q.all(array.map(somefunction)).then(function(){
    console.log("end");
});

function somefunction(array_item){
    var deferred = Q.defer();
    //there is some operations with array_item (does not apply to the problem) and then:
    Q.all(array.map(someanotherfunction)).then(function(){
        deferred.resolve();
    });
    return deferred.promise;
}

function someanotherfunction(array_item){
    var deferred = Q.defer();
    //there is some operations with array_item (does not apply to the problem) and then:
    Q.all(array.map(onemorefunction)).then(function(){
        deferred.resolve();
    });
    return deferred.promise;
}

function onemorefunction(array_item){
    var deferred = Q.defer();
    //some async function with deferred.resolve();
    return deferred.promise;
}
```
So basically my code working perfect. But it becomes "silent" at the somefunction. I will try to explain. After start of execution i see `console.log("end");` immediately. And then knowing promises "nature" all promises get in the "queue" until script comes through all functions. I believe i can fix my problem by pasting each q.all call to the previous function then callback. But i can't do it because of specific chain of execution. So how can I rewrite my code so chain will be the same.

P.S. Sorry for this issue. You can close it if it really awful. I will try to find the fix by myself.

**Comment by kriskowal** [comment]
You may have an exception trapped in an observed promise. Since you’re using `then` with only a fulfillment handler, and not returning the promise returned by `then`, that can happen. Avoiding unnecessary use of `defer()` will help with this:

```js
function someFunction(value) {
    return Q.all(array.map(otherFunction));
}
```
