### ISSUE TITLE
Using jQuery v3+, Q($.ajax) promise returned doesn't seem to resolve

### ISSUE THREAD

**Issue by ericnewton76** [kriskowal/q#833]
Given jquery@3.2.1 and Q@1.5.1 then following code never logs:
```js
Q($.ajax({url:"https://localhost/data"})).then(function(resp) {
   console.log(resp);
});
```

https://jsfiddle.net/enorl76/a4dqskfr/

**Comment by ericnewton76** [comment]
Ugh.  I cannot get jsfiddle to work, cant find an echo service that has the CORS `Access-Allow-Origin: *`

**Comment by kriskowal** [comment]
`then` takes a second argument to catch the error case.

**Comment by ericnewton76** [comment]
https://arbormemorialreview:Arb0rMem0rial!@stage-cremationbasics.cp-access.com/

- Hit "Get Pricing Now", button is towards bottom of page.
- Hit any of the 3 selects, near bottom of page
- Hit "Continue to Step 2"
- Scroll down, Hit "Continue to Step 3"
- Scroll down, Hit "Continue to Step 4"
- Scroll down, Hit "Continue to Step 5"
- On "Build and Price" heading page, click "I'm ready to make arrangements now..."
- Open chrome developer tools, sources, assets/scripts/pricing-bundle.js
- place breakpoints on line 8153,8154
- go back to fill in form, add "TESTING" anywhere in Comments or Notes please
- hit Submit.

Expected behavior: breakpoint on 8154 is hit after Q($.ajax({})) resolves.
