### ISSUE TITLE
Is it possible to use a native Promise object with q ?

### ISSUE THREAD

**Issue by faressoft** [kriskowal/q#836]
Is it possible to use a native Promise object with q ?

```
console.log(typeof q.all([]));
```

Doesn't return a native Promise. Is there anyway to force it to return a native Promise ?

**Comment by kriskowal** [comment]
`Promise.resolve(promise)` will coerce any promise to a standard library promise. All promise methods of all libraries including the standard library will accept another kind of promise, by virtue of "thenability".
