### ISSUE TITLE
Issues with Promise prototype.

### ISSUE THREAD

**Issue by elmanl** [kriskowal/q#842]
Hi,

We use a lot of Promise logic written with q.js in our app.
Here is example how we use it:
```
function myFunction() {
	 var d = Q.defer();
	 myService.getMeSomething()
	 .done(function(data){
		d.resolve(data);
	 ) 
	 return d.promise;
}
....
myFunction().then(....)
```

Now we should use some third party application that use native (MDN) version of Promise and it is cause problem:

```
Uncaught TypeError: Promise.resolve is not a function
    at windowPostMessageProxy.js:235
    at Array.some (<anonymous>)
    at WindowPostMessageProxy.onMessageReceived (windowPostMessageProxy.js:216)
    at WindowPostMessageProxy.windowMessageHandler (windowPostMessageProxy.js:86)
```
There looks like some global namespace issue happening.
Do you have any idea how to address this issue?

Thanks.

**Comment by benjamingr** [comment]
Sure, assimilate promises with `Q()` and you should avoid [explicit construction](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it) :)

**Comment by petermorlion** [comment]
I wasted some time on this, so for anyone in a similar situation, it's:

```
Q(functionReturningNativePromise)
```

not:

```
Q(functionReturningNativePromise())
```
