### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [kriskowal/q#848]
Would you be willing to remove this Google Analytics 'functionality' from this website? There are better alternatives if you _must_ keep tabs on users' activity.

Some reputable alternatives can be seen here: https://switching.software/replace/google-analytics/

**Comment by kriskowal** [comment]
I would welcome a change that removes analytics.

**Comment by resynth1943** [comment]
Oh sure, I can do that right now!

**Comment by resynth1943** [comment]
Do you mind sending me a link to the repository of the website? I can't find it anywhere :-(

**Comment by kriskowal** [comment]
Sure. Can you send a link to the website you’re referring to?

**Comment by resynth1943** [comment]
Well... it's the one that you linked on the homepage. :sweat_smile: http://documentup.com/kriskowal/q/

**Comment by kriskowal** [comment]
Ah, that. That is a service that generates a home page from the README.md, documentup.com. I don’t think we can eliminate their tracker. I can just remove the link. It doesn’t add much value.

**Comment by resynth1943** [comment]
Oh sure, thanks for doing that! :heart:
