### ISSUE TITLE
In v2, not v1, package.json uses deprecated form of license {}

### ISSUE THREAD

**Issue by eemt** [kriskowal/q#852]
Reference: https://docs.npmjs.com/cli/v7/configuring-npm/package-json

> Some old packages used license objects or a "licenses" property ... Those styles are now deprecated.

In v2, **package.json**, you have: 
`  "license": {
    "type": "MIT",
    "url": "http://github.com/kriskowal/q/raw/master/LICENSE"
  },
`
Better to stick with what you have in v1:
`  "license": "MIT",`

**Comment by kriskowal** [comment]
Thankfully, development on `v2` is dead. `v1` forever, or at least until Q itself fades into obscurity.

**Comment by eemt** [comment]
Then I guess I better tell **twilio**, because they are using v2.  (The only reason I noticed this license issue.)

https://github.com/twilio/twilio-node/blob/main/package.json

**Comment by kriskowal** [comment]
Uh, oh. I suppose if it’s working for them, it’s working, even though it never switched to being `latest`.

A PR for the license block change would be welcome. It would also be good to put a `publishConfig` block into `package.json` to make sure the `v2` train doesn’t get promoted to `latest` just in the process of updating the `package.json`.

**Comment by benjamingr** [comment]
> Then I guess I better tell twilio, because they are using v2.

:O

**Comment by benjamingr** [comment]
Q v2, never released officially, forever in beta, is downloaded [500K times every week](https://www.npmjs.com/package/twilio) as a dependency and no one noticed. This is pretty funny.

500 thousand installations every week - not a single bug report ^^ (except this one about the license). We're living in amazing times.
