### ISSUE TITLE
Mark as deprecated on npm?

### ISSUE THREAD

**Issue by jsumners-nr** [kriskowal/q#866]
@kriskowal would you be up for marking this package as deprecated on npm? I am able to see significant usage persisting today despite the notice in the readme and the lack of maintenance/releases over a long period of time. I believe this is due to no visible notice when the package is installed.

**Comment by kriskowal** [comment]
It’s a good idea and would be a worthwhile experiment to see whether it makes a difference. I suspect that the projects that continue to rely on Q are in a deep maintenance mode and would not be moved by warnings. And, deprecation is only really meaningful if it suggests that a project is likely to break if they adopt the next major version. I might be more inclined to deprecate q@^1 if I were planning to introduce a q@^2.

It’s not impossible that I would find a use for q@^2.

I will continue to mull this idea.

**Comment by kriskowal** [comment]
(The reason I would consider making a q@^2 is that native Promises do not support handled-promises or eventual-send https://github.com/endojs/endo/tree/master/packages/eventual-send)

**Comment by jsumners-nr** [comment]
> I suspect that the projects that continue to rely on Q are in a deep maintenance mode and would not be moved by warnings.

That is possible. All I can see is usage statistics that tie `q` usage to Node v20. In my personal time, I have seen that marking a package as deprecated on npm is quite effective at getting people to notice.

**Comment by benjamingr** [comment]
@jsumners-nr the best thing you can do to reduce adoption is probably opening PRs for big packages that have Q as a dependency with a change migrating to native promises

**Comment by jsumners-nr** [comment]
There are over 10,000 direct dependencies of `q` according to npmjs.com. It would be an insurmountable task to determine which packages are still "maintained" and targetable. It is far easier to nip the problem at the source.

**Comment by kriskowal** [comment]
It occurs to me that this is probably my one big chance to say something nice to a lot of people.

**Comment by ljharb** [comment]
@kriskowal deprecation warnings definitely aren't just used for an upcoming major; if a project is effectively sunset, or even if it just won't get further support, a deprecation message is quite appropriate.

**Comment by kriskowal** [comment]
Taking my victory lap now.

<img width="1181" alt="image" src="https://github.com/kriskowal/q/assets/60294/ca905d42-5f83-4813-93e2-334870f2dea9">

**Comment by jsumners-nr** [comment]
Beautiful! Thank you very much for taking the time to consider this and act upon it.

**Comment by lgzhang** [comment]
@kriskowal Excuse me, after q marked as deprecated on npm.  When I install on nodejs 14 version.  It will broken.  Can you recover the download version list.

![image](https://github.com/user-attachments/assets/8a4fee62-d22b-4414-be7b-ab2065a4a663)

**Comment by ljharb** [comment]
Check the box right above that that says “show deprecated versions”. Nothing’s broken by deprecating.

**Comment by lgzhang** [comment]
@ljharb Thanks, But it will be error when npm install on nodejs 14.
![image](https://github.com/user-attachments/assets/95118ea0-9345-4076-853c-df31759103c4)

**Comment by lgzhang** [comment]
And this is a deep dependency，q -->coa -->svgo-->...postcss....-->vue-cli-service@4. I commit a isssue to coa, but the repo is too old and the author not reply.

**Comment by ljharb** [comment]
@lgzhang the error isn't because the package is deprecated, it's because you're using an old and unsupported version of npm. node 14 is also many years EOL, so you should be upgrading that too.

**Comment by lgzhang** [comment]
@ljharb Thanks，It's unfortunate that nodejs 14 is currently being used in the production environment and upgrading is not that easy, it requires approval from the company.
