### ISSUE TITLE
Npm install error，can not download 

### ISSUE THREAD

**Issue by lgzhang** [kriskowal/q#867]
Excuse me, after q marked as deprecated on npm.  When I install on nodejs 14 version.  It will broken.  Can you recover the download version list.
Thanks

![image](https://github.com/user-attachments/assets/12e97a6a-e4da-4f2f-b5c9-34227bfff849)

![image](https://github.com/user-attachments/assets/9b5042d1-abfd-477c-973d-0bf95d392514)

**Comment by kriskowal** [comment]
This is a defect in npm, and I am seeing the same as you. You can recover the version history of Q by cloning the repository and listing tags.

**Comment by lgzhang** [comment]
@kriskowal Thank you very much. But this is a deep dependency，q -->coa -->svgo-->...postcss....-->vue-cli-service@4.   I commit a isssue to coa, but the repo is too old and  the author not reply.

**Comment by kriskowal** [comment]
The WARN lines pertain to the deprecation of q. The ERROR lines below that are unrelated and pertain to an issue with npm, probably temporary networking issues. These output lines are not related. If you can provide isolated steps to reproduce, please update the description and reopen. `npm install coa svgo --ignore-scripts` works locally for me. You may need to specify a version in your instructions.
